//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCLrandom.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DS_QuayThuong
    {
        public long Id { get; set; }
        public string Phone { get; set; }
        public string Code { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Active { get; set; }
        public string PhoneXXX { get; set; }
        public string Time { get; set; }
        public string Type { get; set; }
        public string Duphong { get; set; }
        public Nullable<int> Count { get; set; }
    }
}
